### ISSUE TITLE
Setup-kanbanboard: React-rudx group project

### ISSUE THREAD

**Issue by BB-Simon** [BB-Simon/space-travelers-hub#25]
Hi There!
This is our project link: https://github.com/BB-Simon/space-travelers-hub/projects/1
and we are two developers working on it.

Thanks

**Comment by gemmen29** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 💯 
- Descriptive info ✔️
- Tasks distributed equally ✔️  

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Required Changes ♻️
- [ ] Kindly remove all cards with Team3 in the title since you are a group of two as per this [requirement](https://github.com/microverseinc/curriculum-react-redux/blob/main/group-project/setup_kanban_board.md#:~:text=If%20your%20group%20includes%20two%20people%20%2D%20remove%20all%20cards%20with%20Team3%20in%20the%20title.).

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Shedrack-Sunday** [comment]
Hi @BB-Simon an @atok624 

Congratulations! 🎉 Your project is complete and ready to be merged! 🚀

![image](https://i.pinimg.com/originals/3d/d2/07/3dd207237b39dcacd832f94a35428255.gif)


## Highlights
- Cards setup properly✔️
- Project features assigned   ✔️ 


## Optional Suggestions 💡
While these comments with the [OPTIONAL] prefix won't prevent the approval of this pull request, I strongly recommend taking them into account as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really enhance your application.
Cheers and Happy coding!👏👏👏

If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread, and don't forget to tag me so I'll receive the notification.

As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
